manifest:
  remotes:
    - name: petejohanson
      url-base: https://github.com/petejohanson
    - name: sadekbaroudi
      url-base: https://github.com/sadekbaroudi
  projects:
    - name: cirque-input-module
      remote: petejohanson
      revision: main
    - name: zmk-pmw3610-driver
      remote: sadekbaroudi
      revision: main
